from reportlab.pdfgen import canvas  # type: ignore
from reportlab.lib.pagesizes import letter, A4  # type: ignore
from reportlab.lib.units import inch  # type: ignore
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable  # type: ignore
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle  # type: ignore
from reportlab.lib.enums import TA_CENTER, TA_LEFT  # type: ignore
from pathlib import Path
import time

epoch = time.time()
t = time.localtime(epoch)

d = t.tm_mday
m = t.tm_mon
y = t.tm_year


def Generate_pdf(text_file, output_path):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=50,
        rightMargin=50,
        topMargin=50,
        bottomMargin=50,
    )

    f = open(text_file, "r")
    text = f.read()

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], alignment=TA_CENTER, spaceAfter=20
    )
    meta_style = ParagraphStyle(
        "MetaStyle", parent=styles["Normal"], leading=14, spaceAfter=10
    )
    section_title_style = ParagraphStyle(
        "SectionTitleStyle",
        parent=styles["Heading2"],
        alignment=TA_LEFT,
        spaceBefore=15,
        spaceAfter=8,
    )
    content_style = ParagraphStyle(
        "ContentStyle", parent=styles["Normal"], leading=16, spaceAfter=12
    )

    Story = []
    Story.append(Paragraph("ContentIQ.ai — Professional Transcript", title_style))
    Story.append(Spacer(1, 12))

    video_meta = f"""
    <b>Video Title : </b>Demo video transcript<br/>
    <b>Speaker : </b> John Doe<br/>
    <b>Date : </b>{y}-{m}-{d}<br/>
    <b>Language : </b> English / Hindi Mix<br/>
    <b>Generated by : </b> ContentIQ.ai
    """
    Story.append(Paragraph(video_meta, meta_style)) 
    Story.append(HRFlowable(width="100%", thickness=1, color="black"))
    Story.append(Spacer(1, 15))

    Story.append(Paragraph("Transcript", section_title_style))
    Story.append(Paragraph(text.replace("/n", "<br/>"),  content_style))

    # for line in text.split("/n"):
    #     Story.append(Paragraph(line, content_style))
    #     Story.append(Spacer(1, 10))

    doc.build(Story)
